##
## This file is part of the cupkee project.
##
## Copyright (C) 2016 Lixing Ding <ding.lixing@gmail.com>
##
##

OBJS = main.o
BINARY = open107v

OPENCM3_DIR = ../libopencm3
LDSCRIPT = ../ld/waveshare_open107v.ld

include ../mk/libopencm3.stm32f1x.mk
include ../mk/libopencm3.ruls.mk

