lib_NAMES = sal

sal_SRCS = source/init.c \
		   source/misc.c \
		   source/event.c \
		   source/rbuff.c \
		   source/console.c \
		   source/shell.c \
		   source/timeout.c

sal_CPPFLAGS = -I./include -I../hal/include -I../../panda/include
sal_CFLAGS   =
sal_LDFLAGS  =

include ../../mk/cupkee.ruls.mk

