lib_NAMES = sal

sal_SRCS = source/init.c \
		   source/rbuff.c \
		   source/console.c \
		   source/storage.c

sal_CPPFLAGS = -I./include -I../hal/include
sal_CFLAGS   =
sal_LDFLAGS  =

include ../../mk/cupkee.ruls.mk

