
lib_NAMES = sal

sal_SRCS = atomkernel.c \
		   atomtimer.c \
		   atommutex.c \
		   atomsem.c \
		   atomqueue.c

sal_CPPFLAGS = -I../hal
sal_CFLAGS   =
sal_LDFLAGS  =

include ../../mk/cupkee.ruls.mk

